version: "3.8"

services:
  app:
    build: .
    container_name: mizu_node
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - postgres
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB_NAME: "mizu_node"
      REDIS_URL: "redis://redis:6379/0"
      JWT_VERIFY_KEY: ${JWT_VERIFY_KEY}
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/mizu_node"
    command: ["poetry", "run", "start"]

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "mizu_node"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mizu_node
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: