[tool.poetry]
name = "mizu-node"
version = "0.1.0"
description = ""
authors = ["shudong <dongs2011@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.2"
uvicorn = "^0.31.1"
redis = "^5.1.1"
rq = "^1.16.2"
boto3 = "^1.35.39"
pika = "^1.3.2"
pytest-mock = "^3.14.0"
pytest-mock-resources = {extras = ["redis"], version = "^2.12.1"}
pymongo = "4.10.0"
pyjwt = {extras = ["crypto"], version = "^2.9.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pre-commit = "^4.0.1"
black = "^24.10.0"
isort = "^5.13.2"
pytest-mock-resources = "^2.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dev = "mizu_node.main:start_dev"
start = "mizu_node.main:start"
client = "scripts.client:main"
