class Lang:
    def __init__(self, name: str, last_processed: str = None):
        self.name = name
        self.last_processed = last_processed

    def is_finished(self):
        return self.last_processed is None


LANGUAGES = {
    "aar": Lang("Afar"),
    "abk": Lang("Abkhazian"),
    "afr": Lang("Afrikaans"),
    "aka": Lang("Akan"),
    "amh": Lang("Amharic"),
    "ara": Lang("Arabic"),
    "asm": Lang("Assamese"),
    "aym": Lang("Aymara"),
    "aze": Lang("Azerbaijani"),
    "bak": Lang("Bashkir"),
    "bel": Lang("Belarusian"),
    "ben": Lang("Bengali"),
    "bih": Lang("Bihari languages"),
    "bis": Lang("Bislama"),
    "bod": Lang("Tibetan"),
    "bos": Lang("Bosnian"),
    "bre": Lang("Breton"),
    "bul": Lang("Bulgarian"),
    "cat": Lang("Catalan"),
    "ceb": Lang("Cebuano"),
    "ces": Lang("Czech"),
    "chr": Lang("Cherokee"),
    "cos": Lang("Corsican"),
    "crs": Lang("Seychelles Creole"),
    "cym": Lang("Welsh"),
    "dan": Lang("Danish"),
    "deu": Lang("German"),
    "div": Lang("Divehi"),
    "dzo": Lang("Dzongkha"),
    "ell": Lang("Greek"),
    "eng": Lang("English", last_processed="2ad13af5c13b1b38f27b9c886a121f02"),
    "epo": Lang("Esperanto"),
    "est": Lang("Estonian"),
    "eus": Lang("Basque"),
    "fao": Lang("Faroese"),
    "fas": Lang("Persian"),
    "fij": Lang("Fijian"),
    "fin": Lang("Finnish"),
    "fra": Lang("French"),
    "fry": Lang("Western Frisian"),
    "gla": Lang("Scottish Gaelic"),
    "gle": Lang("Irish"),
    "glg": Lang("Galician"),
    "glv": Lang("Manx"),
    "got": Lang("Gothic"),
    "grn": Lang("Guarani"),
    "guj": Lang("Gujarati"),
    "hat": Lang("Haitian Creole"),
    "hau": Lang("Hausa"),
    "haw": Lang("Hawaiian"),
    "heb": Lang("Hebrew"),
    "hin": Lang("Hindi"),
    "hmn": Lang("Hmong"),
    "hrv": Lang("Croatian"),
    "hun": Lang("Hungarian"),
    "hye": Lang("Armenian"),
    "ibo": Lang("Igbo"),
    "iku": Lang("Inuktitut"),
    "ile": Lang("Interlingue"),
    "ina": Lang("Interlingua"),
    "ind": Lang("Indonesian"),
    "ipk": Lang("Inupiaq"),
    "isl": Lang("Icelandic"),
    "ita": Lang("Italian", last_processed="5cc888580e57b0296a66165d0fa6c5e6"),
    "jav": Lang("Javanese"),
    "jpn": Lang("Japanese"),
    "kal": Lang("Kalaallisut"),
    "kan": Lang("Kannada"),
    "kas": Lang("Kashmiri"),
    "kat": Lang("Georgian"),
    "kaz": Lang("Kazakh"),
    "kha": Lang("Khasi"),
    "khm": Lang("Khmer"),
    "kin": Lang("Kinyarwanda"),
    "kir": Lang("Kyrgyz"),
    "kor": Lang("Korean"),
    "kur": Lang("Kurdish"),
    "lao": Lang("Lao"),
    "lat": Lang("Latin"),
    "lav": Lang("Latvian"),
    "lif": Lang("Limbu"),
    "lin": Lang("Lingala"),
    "lit": Lang("Lithuanian"),
    "ltz": Lang("Luxembourgish"),
    "lug": Lang("Ganda"),
    "mal": Lang("Malayalam"),
    "mar": Lang("Marathi"),
    "mfe": Lang("Mauritian Creole"),
    "mkd": Lang("Macedonian"),
    "mlg": Lang("Malagasy"),
    "mlt": Lang("Maltese"),
    "mon": Lang("Mongolian"),
    "mri": Lang("Maori"),
    "msa": Lang("Malay"),
    "mya": Lang("Burmese"),
    "nau": Lang("Nauru"),
    "nep": Lang("Nepali"),
    "nld": Lang("Dutch"),
    "nno": Lang("Norwegian Nynorsk"),
    "nor": Lang("Norwegian"),
    "nso": Lang("Northern Sotho"),
    "nya": Lang("Nyanja"),
    "oci": Lang("Occitan"),
    "ori": Lang("Oriya"),
    "orm": Lang("Oromo"),
    "pan": Lang("Punjabi"),
    "pol": Lang("Polish"),
    "por": Lang("Portuguese"),
    "pus": Lang("Pashto"),
    "que": Lang("Quechua"),
    "roh": Lang("Romansh"),
    "ron": Lang("Romanian"),
    "run": Lang("Rundi"),
    "rus": Lang("Russian"),
    "sag": Lang("Sango"),
    "san": Lang("Sanskrit"),
    "sco": Lang("Scots"),
    "sin": Lang("Sinhala"),
    "slk": Lang("Slovak"),
    "slv": Lang("Slovenian"),
    "smo": Lang("Samoan"),
    "sna": Lang("Shona"),
    "snd": Lang("Sindhi"),
    "som": Lang("Somali"),
    "sot": Lang("Southern Sotho"),
    "spa": Lang("Spanish"),
    "sqi": Lang("Albanian"),
    "srp": Lang("Serbian"),
    "ssw": Lang("Swati"),
    "sun": Lang("Sundanese"),
    "sux": Lang("Sumerian"),
    "swa": Lang("Swahili"),
    "swe": Lang("Swedish"),
    "syr": Lang("Syriac"),
    "tam": Lang("Tamil"),
    "tat": Lang("Tatar"),
    "tel": Lang("Telugu"),
    "tgk": Lang("Tajik"),
    "tgl": Lang("Tagalog"),
    "tha": Lang("Thai"),
    "tir": Lang("Tigrinya"),
    "ton": Lang("Tonga"),
    "tsn": Lang("Tswana"),
    "tso": Lang("Tsonga"),
    "tuk": Lang("Turkmen"),
    "tur": Lang("Turkish"),
    "uig": Lang("Uighur"),
    "ukr": Lang("Ukrainian"),
    "urd": Lang("Urdu"),
    "uzb": Lang("Uzbek"),
    "ven": Lang("Venda"),
    "vie": Lang("Vietnamese"),
    "vol": Lang("Volapük"),
    "war": Lang("Waray"),
    "wol": Lang("Wolof"),
    "xho": Lang("Xhosa"),
    "yid": Lang("Yiddish"),
    "yor": Lang("Yoruba"),
    "zha": Lang("Zhuang"),
    "zho": Lang("Chinese"),
    "zul": Lang("Zulu"),
    "unknown": Lang("Unknown"),
}
