// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    MIZU_CMC: R2Bucket;
    MIZU_CMC_V2: R2Bucket;
	KV: KVNamespace;
}
